// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PsETXU1qQbPt07Jzv6gZRmVKbgjvN8M',
    appId: '1:739889610243:web:e8dd2dd1d19946a1919836',
    messagingSenderId: '739889610243',
    projectId: 'todo-list-app-61523',
    authDomain: 'todo-list-app-61523.firebaseapp.com',
    storageBucket: 'todo-list-app-61523.firebasestorage.app',
    measurementId: 'G-FCPQXFRSJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7HUj76bHqrsTKNrkm_n0gYhzLJEaFPWA',
    appId: '1:739889610243:android:4005394d2a5fcae8919836',
    messagingSenderId: '739889610243',
    projectId: 'todo-list-app-61523',
    storageBucket: 'todo-list-app-61523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhOj0U75zgUeQjLrjUID_qrRRxpKbtLMo',
    appId: '1:739889610243:ios:071646639e2f4382919836',
    messagingSenderId: '739889610243',
    projectId: 'todo-list-app-61523',
    storageBucket: 'todo-list-app-61523.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhOj0U75zgUeQjLrjUID_qrRRxpKbtLMo',
    appId: '1:739889610243:ios:071646639e2f4382919836',
    messagingSenderId: '739889610243',
    projectId: 'todo-list-app-61523',
    storageBucket: 'todo-list-app-61523.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8PsETXU1qQbPt07Jzv6gZRmVKbgjvN8M',
    appId: '1:739889610243:web:c65162dbf6ea8458919836',
    messagingSenderId: '739889610243',
    projectId: 'todo-list-app-61523',
    authDomain: 'todo-list-app-61523.firebaseapp.com',
    storageBucket: 'todo-list-app-61523.firebasestorage.app',
    measurementId: 'G-RQ66QQ6B8W',
  );
}
