# name: Deploy Flutter Web to Vercel

# on:
#   push:
#     branches:
#       - main # Change this if needed

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Verify Repository Structure
#         run: ls -la # Debugging step to check file locations

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: 3.24.5 # Change to match your Flutter version
#           cache: true

#       - name: Cache Flutter Dependencies
#         uses: actions/cache@v3
#         with:
#           path: ~/.pub-cache
#           key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
#           restore-keys: |
#             flutter-${{ runner.os }}-

#       - name: Change to Flutter Project Directory
#         run: cd src # Move into the Flutter project directory

#       - name: Install Dependencies
#         run: |
#           cd src  # Move into the correct directory
#           flutter pub get

#       - name: Remove .env from pubspec.yaml
#         run: |
#           sed -i '/- .env/d' src/pubspec.yaml

#       # - name: Run Tests
#       #   run: |
#       #     cd src
#       #     flutter test

#       - name: Build Flutter Web
#         run: |
#           cd src
#           flutter build web --release --base-href "/"

#       - name: Install Vercel CLI
#         run: npm install -g vercel@latest

#       - name: Deploy to Vercel
#         run: |
#           cd src/build/web
#           vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm --name kem-jeff-krystelle-first-app

name: Deploy Flutter Web to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          cache: true

      - name: Setup Firebase
        run: npm install -g firebase-tools

      - name: Firebase Auth
        run: firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Setup Environment
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          dart pub global activate flutterfire_cli

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            src/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Install Dependencies
        working-directory: ./src
        run: flutter pub get

      - name: Configure Firebase
        working-directory: ./src
        run: flutterfire configure --yes --project=todo-list-app-61523

      - name: Build Production
        working-directory: ./src
        run: |
          flutter build web \
            --release \
            --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/ \
            --pwa-strategy=none

      - name: Deploy
        working-directory: ./src/build/web
        run: |
          vercel --prod --confirm \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --name kem-jeff-krystelle-first-app
